package com.oop.task_3_2;

public enum DisciplineType {
    //*
    HISTORY,
    PHILOSOPHY,
    GROUP_PROJECT,
    BUSINESS_ENGLISH,
    PHYSICAL_CULTURE,
    FOREIGN_LANGUAGE,
    OPERATING_SYSTEMS,
    PARALLELISM_THEORY,
    COMPUTING_PLATFORMS,
    COMPUTATIONAL_MODELS,
    IMPERATIVE_PROGRAMMING,
    DECLARATIVE_PROGRAMMING,
    OBJECT_ORIENTED_PROGRAMMING,
    PHYSICAL_CULTURE_FACULTATIVE,
    PROGRAMMABLE_MICROCONTROLLERS,
    FUNDAMENTALS_OF_SPEECH_CULTURE,
    INTRODUCTION_TO_COMPUTER_NETWORKS,
    INTRODUCTION_TO_ARTIFICIAL_INTELLIGENCE,
    DIFFERENTIAL_EQUATIONS_AND_COMPLEX_ANALYSES,
    PROBABILITY_THEORY_AND_MATHEMATICAL_STATISTICS,
    INTRODUCTION_TO_ALGEBRA_AND_MATHEMATICAL_ANALYSIS,
    INTRODUCTION_TO_DISCRETE_MATHS_AND_MATHEMATICAL_LOGIC,
    INTRODUCTION_TO_ANALOG_ELECTRONICS_AND_MEASUREMENT_TECHNIQUES,
    QUALIFICATION_ASSIGNMENT
}
